language: php
sudo: required
dist: trusty
php:
  - 7.1
services:
  - docker
before_script:
  - composer self-update
  - docker run -d -p 127.0.0.1:8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin jboss/keycloak