language: php
sudo: required
dist: trusty
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
services:
  - docker
before_script:
  - docker run -d -p 127.0.0.1:8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin jboss/keycloak
before_install:
    - travis_retry composer self-update
install:
    - travis_retry composer install --no-interaction --prefer-dist
script:
    - vendor/bin/phpunit --verbose